### ISSUE TITLE
error while running estimate_recs_trained_mdl.py - NaN values

### ISSUE THREAD

**Issue by MatanArgaman** [Dinstein-Lab/ASDSpeech#2]
run parameters:
-c ../config/config_file_trained_mdl.yaml

Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2024.1.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1535, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2024.1.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\PycharmProjects\ASDSpeech\code_base\estimate_recs_trained_mdl.py", line 153, in <module>
    score = int(row[target_score])
ValueError: cannot convert float NaN to integer
python-BaseException

**Comment by marinaEni** [comment]
thank you. the bug is fixed.
added a row: 
test_df['rec_id'] = test_df['rec_id'].astype(str)
after:
test_df = test_sets_df[test_set]
